/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteRouteImport } from './routes/_unauthenticated/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnauthenticatedLoginRouteImport } from './routes/_unauthenticated/login'
import { Route as AuthenticatedCrudRouteImport } from './routes/_authenticated/crud'
import { Route as PublicMiniaturesIndexRouteImport } from './routes/_public/miniatures/index'
import { Route as PublicMiniaturesIdRouteImport } from './routes/_public/miniatures/$id'

const UnauthenticatedRouteRoute = UnauthenticatedRouteRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedLoginRoute = UnauthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UnauthenticatedRouteRoute,
} as any)
const AuthenticatedCrudRoute = AuthenticatedCrudRouteImport.update({
  id: '/crud',
  path: '/crud',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PublicMiniaturesIndexRoute = PublicMiniaturesIndexRouteImport.update({
  id: '/_public/miniatures/',
  path: '/miniatures/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicMiniaturesIdRoute = PublicMiniaturesIdRouteImport.update({
  id: '/_public/miniatures/$id',
  path: '/miniatures/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crud': typeof AuthenticatedCrudRoute
  '/login': typeof UnauthenticatedLoginRoute
  '/miniatures/$id': typeof PublicMiniaturesIdRoute
  '/miniatures/': typeof PublicMiniaturesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crud': typeof AuthenticatedCrudRoute
  '/login': typeof UnauthenticatedLoginRoute
  '/miniatures/$id': typeof PublicMiniaturesIdRoute
  '/miniatures': typeof PublicMiniaturesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteRouteWithChildren
  '/_authenticated/crud': typeof AuthenticatedCrudRoute
  '/_unauthenticated/login': typeof UnauthenticatedLoginRoute
  '/_public/miniatures/$id': typeof PublicMiniaturesIdRoute
  '/_public/miniatures/': typeof PublicMiniaturesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crud' | '/login' | '/miniatures/$id' | '/miniatures/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crud' | '/login' | '/miniatures/$id' | '/miniatures'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_authenticated/crud'
    | '/_unauthenticated/login'
    | '/_public/miniatures/$id'
    | '/_public/miniatures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  UnauthenticatedRouteRoute: typeof UnauthenticatedRouteRouteWithChildren
  PublicMiniaturesIdRoute: typeof PublicMiniaturesIdRoute
  PublicMiniaturesIndexRoute: typeof PublicMiniaturesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/login': {
      id: '/_unauthenticated/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthenticatedLoginRouteImport
      parentRoute: typeof UnauthenticatedRouteRoute
    }
    '/_authenticated/crud': {
      id: '/_authenticated/crud'
      path: '/crud'
      fullPath: '/crud'
      preLoaderRoute: typeof AuthenticatedCrudRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/miniatures/': {
      id: '/_public/miniatures/'
      path: '/miniatures'
      fullPath: '/miniatures/'
      preLoaderRoute: typeof PublicMiniaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/miniatures/$id': {
      id: '/_public/miniatures/$id'
      path: '/miniatures/$id'
      fullPath: '/miniatures/$id'
      preLoaderRoute: typeof PublicMiniaturesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCrudRoute: typeof AuthenticatedCrudRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCrudRoute: AuthenticatedCrudRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface UnauthenticatedRouteRouteChildren {
  UnauthenticatedLoginRoute: typeof UnauthenticatedLoginRoute
}

const UnauthenticatedRouteRouteChildren: UnauthenticatedRouteRouteChildren = {
  UnauthenticatedLoginRoute: UnauthenticatedLoginRoute,
}

const UnauthenticatedRouteRouteWithChildren =
  UnauthenticatedRouteRoute._addFileChildren(UnauthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  UnauthenticatedRouteRoute: UnauthenticatedRouteRouteWithChildren,
  PublicMiniaturesIdRoute: PublicMiniaturesIdRoute,
  PublicMiniaturesIndexRoute: PublicMiniaturesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
